all:
	g++  -o jack_fft jack_fft.cpp -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3
	g++  -o music3 music3.cpp -std=c++11 -pthread -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3 
	g++  -o music3_no music3_no.cpp -std=c++11 -pthread -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3 
	