all:
	#g++  -o gsc gsc.cpp -std=c++11 -pthread -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3 
	#g++  -o das das.cpp -std=c++11 -pthread -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3 
	g++  -o freqmask freqmask.cpp -std=c++11 -pthread -ljack -lsndfile -lfftw3 -lm -I /usr/include/eigen3 
